### ISSUE TITLE
Pakkaan meno

### ISSUE THREAD

**Issue by Wilsko** [Bizhop/jassu#42]
Katsottiin säännöt Alapon kanssa. Ne vähän vaihtelevat, minun kirjaamani ovat ne millä me on pelattu meidän kirvesporukassa.

Pakkaan saa mennä
- ajojen välissä jos ei ole valttia kädessä
- ennen ensimmäistä ajoa
- pelin alussa ajovuorossa oleva ei saa mennä pakkaan, yksi kortti on pelattava

Näillä mennään.

Pekan kirjassa on tiukempi linja:
"Pakkaan saa mennä vielä kun on lyönyt yhden kortin ja katsonut seuraavan kortin omaan lyöntivuoroonsa saakka. Tätä myöhemmin ei pakkaan saa mennä vaikka se olisi taktisesti edullista"
Sääntöversiot -kohdassa on mainittu 
Versio 1: Pampuitta pakkaan eli pakkaan ei saa mennä jos on pamppuja
Versio 2:  Ilman valttia pakkaan, eli pakkaan ei mennä jos on valtteja

**Comment by Bizhop** [comment]
Vielä näköjään jäi sillä tavalla, että pakkaan voi mennä muutenkin kun ajojen välissä. Se lienee liian "taktisesti" vapaata, joten laitetaan siihen vielä rajoitus.

**Comment by Bizhop** [comment]
Tässä viimeiset korjaukset #49 . Suljen tämän lapun nyt, palataan tähän jos tarvetta.
